# Generated by Django 4.2.11 on 2024-11-14 07:35

import app.utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(default=app.utils.utils.get_char_uuid, max_length=100, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('profile', models.FileField(max_length=255, upload_to=app.utils.utils.kyc_path)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
