# Generated by Django 4.2.11 on 2024-11-14 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.URLField(max_length=255),
        ),
    ]
